[alembic]
script_location = src/database/migrations
file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s
prepend_sys_path = .
sqlalchemy.url = postgresql+asyncpg://storyforge:storyforge_pass@localhost:5432/storyforge_db

[post_write_hooks]

[logging]
default_level = INFO
